spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}

auth:
  jwt:
    token:
      secret-key: ${JWT_TOKEN_SECRET_KEY}
      access:
        expire-time: ${ACCESS_TOKEN_EXPIRED_TIME_MS}
      refresh:
        expire-time: ${REFRESH_TOKEN_EXPIRED_TIME_MS}

password:
  salt: ${password.salt}
  algorithm: ${password.algorithm}
