name: Java CD with Gradle

on:
  push:
    branches: [ "be-dev" ]

permissions:
  contents: read

env:
  RESOURCE_PATH: ./backend/src/main/resources/application.yaml

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set yml file 
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.RESOURCE_PATH }} 
        env:
          spring.datasource.url: ${{ secrets.DB_HOST }} 
          spring.datasource.username: ${{ secrets.DB_USERNAME }} 
          spring.datasource.password: ${{ secrets.DB_PASSWORD }} 
          auth.jwt.token.secret-key: ${{ secrets.JWT_SECRET_KEY }}
          auth.jwt.token.access.expire-time: ${{ secrets.ACCESS_EXPIRE_TIME_MS }}
          auth.jwt.token.refresh.expire-time: ${{ secrets.REFRESH_EXPIRE_TIME_MS }}
          password.salt: ${{ secrets.PASSWORD_SALT }}
          password.algorithm: ${{ secrets.ALGORITHM }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: buildJar
          path: backend/build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: buildJar

      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "*.jar"
          target: "~"

  SSH:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ssh to ec2 for run spring jar
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          script: |
            sudo fuser -k 8080/tcp
            sudo nohup java -jar ~/*.jar > nohup.out 2> nohup.err < /dev/null &
            exit
